bigdata/bigdata/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls', namespace='movies'))
]

bigdata/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index),
    path('api/genres_count', views.genres_count, name='genres_count'),

    # path('movies/', include('movies.urls'))
]

bigdata/movies/models.py
# from django.db import models
from djongo import models
from django.conf import settings as djangoSettings
import os,csv
import pymongo
# Create your models here.

class ProductionCompany(models.Model):
    company_id = models.IntegerField()
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class ProductionCountry(models.Model):
    country_id = models.CharField(max_length=200)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class SpokenLanguage(models.Model):
    language_id = models.CharField(max_length=200)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Genre(models.Model):
    genre_id = models.IntegerField()
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def list_of_genres():
        conn = pymongo.MongoClient('localhost', 27017)

        db = conn.get_database('moviedb')
        collection = db.get_collection('movies_genre')
        genre_list = collection.distinct('name')

        return genre_list

    def count_genres(self, queryset):
        genres = []

        for movie in queryset:
            m_genres = movie.genres(manager='objects').all()
            for genre in m_genres:
                if len(genres) == 0:
                    new_one = {'genre' : genre.name, 'count' : 1}
                    genres.append(new_one)
                    print(genre.name + " Added // genres len : " + str(len(genres)))
                else:
                    length = len(genres)
                    count = 1
                    for g in genres:
                        if genre.name == g['genre']:
                            g['count'] += 1  
                            print(genre.name + " + 1")
                            break
                        elif count == length:
                            new_one = {'genre' : genre.name, 'count' : 1}
                            genres.append(new_one)
                            print(genre.name + " Added // genres len : " + str(len(genres)))
                            break
                        else:
                            count+=1
        import csv    
        f = open('/Users/move0/dev/django/bigdata/bigdata/static/movies/data/recent_genre.csv', 'w', encoding='utf-8', newline='')
        wr = csv.writer(f)
        wr.writerow(['name', 'count'])
        for line in genres:
            newline = [line['genre'], line['count']]
            wr.writerow(newline)
        f.close()
        return

class Collection(models.Model):    
    collection_id = models.IntegerField(default=0)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=200)
    movie_id = models.IntegerField()
    imdb_id = models.CharField(blank=True, max_length=200)
    overview = models.CharField(max_length=200)
    popularity = models.FloatField(default=0)
    poster = models.URLField()
    production_companies = models.ManyToManyField(ProductionCompany)
    production_countries = models.ManyToManyField(ProductionCountry)
    release_date = models.DateField()
    revenue = models.IntegerField(default=0)
    runtime = models.IntegerField(default=0)
    spoken_languages = models.ManyToManyField(SpokenLanguage)
    status = models.CharField(max_length=200)
    tagline = models.CharField(max_length=200)
    video = models.BooleanField()
    genres = models.ManyToManyField(Genre)
    vote_avg = models.FloatField(default=0)
    vote_count = models.IntegerField(default=0)
    original_language = models.CharField(max_length=200)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class User(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def set_preference_tag(self):
        genre_list = Genre.list_of_genres()
        genre_dict = {}

        for g in genre_list:
            genre_dict[g] = []
        
        for rating in self.ratings(manager="objects").all():
            mov = Movie.objects.get(id=rating.movie_id)
            genres = mov.genres(manager="objects").all()
            for genre in genres:
                genre_dict[genre.name].append(rating.rating)
        
        for k,v in genre_dict.items():
            if len(v) > 0:
                avg = sum(v) / len(v)
                pref = self.preferences(manager="objects").create(genre=k, avg_rating=avg)
                pref.save()

        # self.preferences = genre_json
        # self.save()


class PrefTag(models.Model):
    genre = models.CharField(max_length=200)
    avg_rating = models.FloatField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name="preferences")

    def __str__(self):
        return self.genre + str(self.avg_rating)


class Rating(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, default=None, related_name="ratings")
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name="ratings")
    rating = models.FloatField(default=0)

bigdata/movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
import datetime, pymongo, json
from .models import Movie, Genre
from django.db import connections
from django.db.models import Count
import mimetypes

# from .forms import PostForm, CommentForm

def index(request):
    movies = Movie.objects.filter(release_date__gte=datetime.date(2017,5,1))        
    return render(request, 'movies/index.html',{
        'movies' : movies
    })

def genres_count(request):
    filename = '/Users/move0/dev/django/bigdata/bigdata/static/movies/data/recent_genre.csv'
    fsock = open(filename,"rb")
    return HttpResponse(fsock, content_type=mimetypes.guess_type(filename)[0]) 

bigdata/movies/templates/movies/base.html
{% load static %}

<html>
    <head>
        <title>Movies</title>
        <script src="{% static 'movies/js/d3.js' %}"></script> 
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <style>
            body{
                margin : 50px;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <h1><a href="/movies">Movies</a></h1>
        </div>
        <div class="content">
            {% block content%}
            {% endblock %}
        </div>
    </body>
</html>

bigdata/movies/templates/movies/index.html
{% extends 'movies/base.html' %}

{% block content %}
<!-- Create a div where the graph will take place -->
<div id="my_dataviz"></div>

<script>

// set the dimensions and margins of the graph
var margin = {top: 30, right: 30, bottom: 70, left: 60},
    width = 460 - margin.left - margin.right,
    height = 400 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#my_dataviz")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

// Parse the Data
d3.csv("{% url 'movies:genres_count' %}", function(error, data) {
    // X axis
    var x = d3.scaleBand()
    .range([ 0, width ])
    .domain(data.map(function(d) { return d.name; }))
    .padding(0.2);''
    svg.append("g")
    .attr("transform", "translate(0," + height + ")")
    .call(d3.axisBottom(x))
    .selectAll("text")
        .attr("transform", "translate(-10,0)rotate(-45)")
        .style("text-anchor", "end");

    // Add Y axis
    var y = d3.scaleLinear()
    .domain([0, 500])
    .range([ height, 0]);
    svg.append("g")
    .call(d3.axisLeft(y));

    // Bars
    svg.selectAll("mybar")
    .data(data)
    .enter()
    .append("rect")
        .attr("x", function(d) { return x(d.name); })
        .attr("y", function(d) { return y(d.count); })
        .attr("width", x.bandwidth())
        .attr("height", function(d) { return height - y(d.count); })
        .attr("fill", "#69b3a2")

})
</script>

<hr>

<div class="row">
{% for movie in movies %}
    <div class="col-md-3">
      <div class="card" style="width: 18rem; margin-bottom:20px">
          <img src="https://image.tmdb.org/t/p/w500{{movie.poster}}" class="card-img-top" alt="..." width="286px" height="386px">
          <div class="card-body">
              <h5 class="card-title">{{movie.title}}</h5>
              <p class="card-text">{{movie.overview | truncatechars:25}}</p>
              <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
      </div>
    </div>
<br>
{% endfor %}
</div>
{% endblock %}